# Generated by Django 4.1.3 on 2022-11-18 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobileName', models.CharField(max_length=20)),
                ('mobileModel', models.CharField(max_length=20)),
                ('ram', models.IntegerField()),
                ('storage', models.IntegerField()),
                ('color', models.CharField(max_length=20)),
            ],
        ),
    ]
