# Generated by Django 4.1.3 on 2022-11-23 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_app', '0003_mixinmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('salary', models.IntegerField()),
                ('department', models.CharField(max_length=20)),
                ('designation', models.CharField(max_length=20)),
                ('company', models.CharField(max_length=20)),
            ],
        ),
    ]
