# Generated by Django 4.1.3 on 2022-11-24 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_app', '0004_employeemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='carModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Car_name', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('engine', models.CharField(max_length=20)),
                ('owners_name', models.CharField(max_length=20)),
            ],
        ),
    ]
