# Generated by Django 4.1.3 on 2022-11-25 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_app', '0005_carmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=50)),
                ('no_of_seats', models.IntegerField()),
                ('streaming_time', models.CharField(max_length=20)),
                ('streaming_date', models.DateField()),
                ('Theatre_name', models.CharField(max_length=30)),
            ],
        ),
    ]
