# Generated by Django 4.1.3 on 2022-11-25 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_app', '0006_moviemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_nane', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
