# Generated by Django 4.1.3 on 2022-11-25 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_app', '0007_personmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personmodel',
            old_name='last_nane',
            new_name='last_name',
        ),
    ]
